name: 'LeetCode Sync'
description: 'Sync LeetCode submissions to GitHub'
branding: 
  icon: git-commit
  color: yellow
inputs:
  user:
    description: 'The user to sync'
    required: false
  github-token:
    description: 'The GitHub token'
    required: true
  leetcode-csrf-token:
    description: 'The LeetCode CSRF token'
    required: true
  leetcode-session:
    description: 'The LeetCode session value'
    required: true
  filter-duplicate-secs:
    description: 'Number of seconds after an accepted solution to ignore other accepted solutions for the same problem'
    required: false
    default: 86400
runs:
  using: 'node12'
  main: 'index.js'